import Head from "next/head";
import Films from "../components/Films";
import Main from "../components/Main";
import { H1Wrap } from "../components/H1";
import { TextWrap } from "../components/Text";
import styled from "styled-components";
import { rem } from "polished";
import Header from "../components/Header";

export default function Home({ films = [] }) {
  return (
    <>
      <Head>
        <title>Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <HomeTitle>MaileHereko</HomeTitle>
        <HomeText>
          List of movies and TV Shows, I,{" "}
          <HomeTextPrimary>Pramod Poudel</HomeTextPrimary> have watched till
          date. Explore what I have watched and also feel free to make a
          suggestion. 😉
        </HomeText>
        <Films films={films} />
      </Main>
    </>
  );
}

const HomeTitle = styled(H1Wrap)`
  margin-bottom: ${rem(16)};
`;

const HomeText = styled(TextWrap)`
  margin-bottom: ${rem(24)};
`;

const HomeTextPrimary = styled.span`
  display: inline;
  color: ${(props) => props.theme.colors.primary};
`;

// export async function getStaticProps() {
//   return fetch("https://json-server-gilt.vercel.app/films")
//     .then((res) => res.json())
//     .then((films) => {
//       return {
//         props: { films },
//       };
//     });
// }

export async function getStaticProps() {
  return fetch("https://kinopoiskapiunofficial.tech/api/v2.2/films/", {
    method: "GET",
    headers: {
      "X-API-KEY": "4f35a3fb-8eaf-495d-a1e5-53a389c3c2a8",
      "Content-Type": "application/json",
    },
  })
    .then((res) => res.json())
    .then((films) => {
      return {
        props: { films },
      };
    });
}
